"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function (o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
        desc = { enumerable: true, get: function () { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function (o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function (o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function (o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function (o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.createDictionary = createDictionary;
exports.addToDictionary = addToDictionary;
exports.hashToName = hashToName;
exports.nameToHash = nameToHash;
exports.loadDictionary = loadDictionary;
exports.loadDictionaryText = loadDictionaryText;
exports.saveDictionary = saveDictionary;
exports.loadDictionariesFromDir = loadDictionariesFromDir;
exports.createAndLoadDictionaries = createAndLoadDictionaries;
const fs = __importStar(require("fs"));
const path = __importStar(require("path"));
const hash_1 = require("./hash");
/**
 * Create an empty hash dictionary
 */
function createDictionary() {
    const dict = {
        hashToName: new Map(),
        nameToHash: new Map()
    };
    // Pre-populate with numeric keys 0..10000 (covers everything the reader's
    // TableInt fallback used to brute-force).
    for (let i = 0; i <= 10000; i++) {
        const name = i.toString();
        const h = (0, hash_1.hash)(name);
        dict.hashToName.set(h, name);
        dict.nameToHash.set(name, h);
    }
    return dict;
}
/**
 * Add a name to the dictionary
 */
function addToDictionary(dict, name) {
    const h = (0, hash_1.hash)(name);
    dict.hashToName.set(h, name);
    dict.nameToHash.set(name, h);
    return h;
}
/**
 * Resolve a hash to a name (or null if unknown)
 */
function hashToName(dict, h) {
    return dict.hashToName.get(h) ?? null;
}
/**
 * Get hash for a name, adding to dictionary if new
 */
function nameToHash(dict, name) {
    // Check if it's already a hex hash
    if ((0, hash_1.isHexHash)(name)) {
        return (0, hash_1.hexToHash)(name);
    }
    const existing = dict.nameToHash.get(name);
    if (existing !== undefined)
        return existing;
    return addToDictionary(dict, name);
}
/**
 * Load a dictionary file in RGD_DIC format
 * Format:
 *   #RGD_DIC (header)
 *   0xHASH=name
 *   # comments
 */
function loadDictionary(dict, filePath) {
    loadDictionaryText(dict, fs.readFileSync(filePath, 'utf8'));
}
// rgd-git: load from a string, so the dictionary can be embedded in a standalone executable.
function loadDictionaryText(dict, content) {
    const lines = content.split(/\r?\n/);
    let count = 0;
    for (const line of lines) {
        // Skip comments and empty lines
        const trimmed = line.trim();
        if (!trimmed || trimmed.startsWith('#'))
            continue;
        // Parse 0xHASH=name format
        const eqPos = trimmed.indexOf('=');
        if (eqPos === -1)
            continue;
        const hashPart = trimmed.slice(0, eqPos).trim();
        const namePart = trimmed.slice(eqPos + 1).trim();
        if (!hashPart.toLowerCase().startsWith('0x'))
            continue;
        const h = (0, hash_1.hexToHash)(hashPart);
        if (namePart && !dict.hashToName.has(h)) {
            dict.hashToName.set(h, namePart);
            dict.nameToHash.set(namePart, h);
            count++;
        }
    }

}
/**
 * Save custom dictionary entries to a file
 */
function saveDictionary(dict, filePath, customOnly = null) {
    let content = '#RGD_DIC\n# RGD Hash Dictionary\n# Generated by rgd-tools\n\n';
    const entries = [];
    for (const [h, name] of dict.hashToName) {
        // Skip numeric keys (built-in)
        if (/^\d+$/.test(name))
            continue;
        if (customOnly && !customOnly.has(h))
            continue;
        entries.push([h, name]);
    }
    // Sort by hash
    entries.sort((a, b) => a[0] - b[0]);
    for (const [h, name] of entries) {
        content += `${(0, hash_1.hashToHex)(h)}=${name}\n`;
    }
    fs.writeFileSync(filePath, content, 'utf8');
}
/**
 * Scan a directory for dictionary files and load them all
 */
function loadDictionariesFromDir(dict, dirPath) {
    if (!fs.existsSync(dirPath))
        return;
    const files = fs.readdirSync(dirPath);
    for (const file of files) {
        if (file.endsWith('.dic') || file.endsWith('.txt')) {
            try {
                loadDictionary(dict, path.join(dirPath, file));
            }
            catch (e) {
                // Ignore errors loading individual dictionary files
            }
        }
    }
}
/**
 * Create a dictionary and load common dictionaries
 */
function createAndLoadDictionaries(dictionaryPaths = []) {
    const dict = createDictionary();
    // Load from provided paths
    for (const p of dictionaryPaths) {
        if (fs.existsSync(p)) {
            const stat = fs.statSync(p);
            if (stat.isDirectory()) {
                loadDictionariesFromDir(dict, p);
            }
            else {
                loadDictionary(dict, p);
            }
        }
    }
    return dict;
}
